format = "\n$directory$git_branch$git_status\n$character"

add_newline = false
command_timeout = 2000

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false

[fill]
symbol = " "

[directory]
disabled = false
style = "fg:#FFFFFF bg:#1995ad bold"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = ".../"
read_only = "  "
read_only_style = "fg:#FFFFFF bg:#1995ad"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:#5c6d74"
format = "[[ $symbol $branch ](fg:#FFFFFF bg:#5c6d74)]($style)"

[git_status]
style = "bg:#5c6d74"
format = "[[($all_status$ahead_behind )](fg:#FFFFFF bg:#5c6d74)]($style)"

[cmd_duration]
min_time = 1
style = "fg:#e0af68"
format = "[$duration]($style)"

[time]
disabled = false
time_format = "%R"
format = "[[   $time ](fg:#a0a9cb)]($style)"

[character]
vimcmd_symbol = "[V](bold green) "
